// vue/src/components/TodoList.vue
<script lang="ts">
   import { ref, watch, defineProps, defineEmits } from 'vue';
   import { Todo } from '../types/todo';


   export default {
      props: {
         todoList: {
            type: Array as () => Todo[],
            required: true
         }
      },
      emits: ['update-todo'],
      setup(props, { emit }) {

         const localTodoList = ref<Todo[]>([...props.todoList]);

         watch(() => props.todoList, 
         (newTodoList) => {
            localTodoList.value = [...newTodoList];
         }, { deep: true });

         const getTodos = () => {
            fetch('http://localhost:3000/todo')
               .then(res => res.json())
               .then(data => {
                  localTodoList.value = data;
                  emit('update-todo', data);
               });
         }

         const updateList = (todo: Todo) => {
            fetch(`http://localhost:3000/todo/${todo.id}`, {
               method: 'PATCH',
               headers: {
                  'Content-Type': 'application/json'
               },
               body: JSON.stringify({
                  done: todo.done
               })
            })
            .then(() => {
               const newArray = localTodoList.value.map(item => {
                  return item.id === todo.id ? { ...item, done: item.done } : item
               })
               emit('update-todo', newArray);
            })
         }

         getTodos();

         return {
            todoList: localTodoList,
            updateList
         }
      }
   }
</script>

<template>
   <ul>
      <li 
         v-for="todo in todoList" :key="todo.id"
         @click="todo.done = !todo.done; updateList(todo)"
      >
         {{ todo.done ? "✅" : "❌" }}{{ todo.title }}
      </li>
   </ul>
</template>



<style>

</style>

// svelte/src/lib/TodoList.svelte
<script lang="ts">
   import { onMount } from "svelte";
   import { todoList } from "../store.ts";
   import type { Todo } from "../types.ts";

   

   onMount(() => {
      fetch('http://localhost:3000/todo')
         .then(res => res.json())
         .then(data => {
            console.log(data);
            console.log('state före', $todoList);
            todoList.set(data);
            console.log('state efter', $todoList);
         })
   });

   const updateTodo = (todo:Todo) => {      
      fetch(`http://localhost:3000/todo/${todo.id}`, {
         method: 'PATCH',
         headers: {
            'Content-Type': 'application/json'
         },
         body: JSON.stringify({ done: !todo.done })
      })
         .then(() => {
            todoList.update(allTodos => {
               return allTodos.map(currentTodo => {
                  return currentTodo.id === todo.id ? { ...currentTodo, done: !currentTodo.done } : currentTodo
               })
            });
         })
   }

</script>

<ul>
   {#each $todoList as todo}
      <li on:click={() => updateTodo(todo)}>{todo.done ? '✅' : '❌'}{todo.title}</li>
   {/each}
</ul>
